import turtle as tl
sc = tl.Screen()
sc.bgcolor("black")
sc.setup(600.600)
main = tl.Turtle()
main.color("red")
colors = ["red", "blue", "yellow", "orange", "white"]
main.forward(100)
main.right(90)
main.forward(100)
main.right(90)
main.forward(100)
main.right(90)
main.forward(100)
main.right(135)
main.forward(140)
main.right(135)
main.penup()
main.forward(98)
main.pendown()
main.right(135)
main.forward(140)
main.penup()
main.forward(200)
main.pendown()
tl.done()